FROM php:8.0-fpm-alpine

RUN docker-php-ext-install pdo pdo_mysql opcache
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html
COPY . .
RUN composer install --no-dev --no-interaction --optimize-autoloader && \
    php bin/console cache:clear --env=prod

EXPOSE 9000
CMD ["php-fpm"]
